const PRESET_CODES = [
  { _id: '1', name: 'Code Silver', color: '#C0C0C0', meaning: 'Indicates that the person is feeling grateful or appreciative.' },
  { _id: '2', name: 'Code Gold', color: '#FFD700', meaning: 'Indicates that the person is feeling proud or accomplished.' },
  { _id: '3', name: 'Code Teal', color: '#008080', meaning: 'Indicates that the person is feeling curious or interested.' },
  { _id: '4', name: 'Code Navy', color: '#000080', meaning: 'Indicates that the person is feeling serious or contemplative.' },
  { _id: '5', name: 'Code Maroon', color: '#800000', meaning: 'Indicates that the person is feeling overwhelmed or stressed.' },
  { _id: '6', name: 'Code Turquoise', color: '#40E0D0', meaning: 'Indicates that the person is feeling creative or imaginative.' },
  { _id: '7', name: 'Code Olive', color: '#808000', meaning: 'Indicates that the person is feeling peaceful or serene.' },
  { _id: '8', name: 'Code Magenta', color: '#FF00FF', meaning: 'Indicates that the person is feeling adventurous or daring.' },
  { _id: '9', name: 'Code Indigo', color: '#4B0082', meaning: 'Indicates that the person is feeling spiritual or mystical.' },
  { _id: '10', name: 'Code Crimson', color: '#DC143C', meaning: 'Indicates that the person is feeling passionate or enthusiastic.' },
  { _id: '11', name: 'Code Lavender', color: '#E6E6FA', meaning: 'Indicates that the person is feeling nostalgic or sentimental.' },
  { _id: '12', name: 'Code Amber', color: '#FFBF00', meaning: 'Indicates that the person is feeling cautious or hesitant.' },
  { _id: '13', name: 'Code Cyan', color: '#00FFFF', meaning: 'Indicates that the person is feeling optimistic or hopeful.' },
  { _id: '14', name: 'Code Blue', color: '#0000FF', meaning: 'Indicates that the person is feeling sad or depressed.' },
  { _id: '15', name: 'Code Red', color: '#FF0000', meaning: 'Indicates that the person is angry or frustrated.' },
  { _id: '16', name: 'Code Green', color: '#008000', meaning: 'Indicates that the person is feeling jealous.' },
  { _id: '17', name: 'Code Yellow', color: '#FFFF00', meaning: 'Indicates that the person is feeling anxious or nervous.' },
  { _id: '18', name: 'Code Purple', color: '#800080', meaning: 'Indicates that the person is feeling romantic or flirty.' },
  { _id: '19', name: 'Code Orange', color: '#FFA500', meaning: 'Indicates that the person is feeling energized or excited.' },
  { _id: '20', name: 'Code Law', color: '#E3A857', meaning: 'Indicates that the person needs help or support.' },
  { _id: '21', name: 'Code Key', color: '#B8860B', meaning: 'Indicates that the person wants to talk in private or needs a secret meeting.' },
  { _id: '22', name: 'Code Gray', color: '#808080', meaning: 'Indicates that the person is feeling confused or uncertain.' },
  { _id: '23', name: 'Code Pink', color: '#FFC0CB', meaning: 'Indicates that the person is feeling happy or content.' },
  { _id: '24', name: 'Code Black', color: '#000000', meaning: 'Indicates that the person is feeling angry or upset.' },
  { _id: '25', name: 'Code Brown', color: '#A52A2A', meaning: 'Indicates that the person is feeling embarrassed or ashamed.' },
  { _id: '26', name: 'Code White', color: '#FFFFFF', meaning: 'Indicates that the person is feeling peaceful or relaxed.' },
  { _id: '27', name: 'Code Lec', color: '#ADD8E6', meaning: 'Class' },
  { _id: '28', name: 'Code Heavy Blue', color: '#00008B', meaning: 'Lonely' },
];

module.exports = { PRESET_CODES };
